/*
 * Moosend API
 * TODO: Add a description
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.swagger.client.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import io.swagger.client.model.CustomField;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;

/**
 * Context37
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2017-10-03T15:14:23.257Z")
public class Context37 {
  @SerializedName("CreatedOn")
  private String createdOn = null;

  @SerializedName("CustomFields")
  private List<CustomField> customFields = null;

  @SerializedName("Email")
  private String email = null;

  @SerializedName("ID")
  private String ID = null;

  @SerializedName("Name")
  private String name = null;

  @SerializedName("RemovedOn")
  private String removedOn = null;

  @SerializedName("SubscribeMethod")
  private Double subscribeMethod = null;

  @SerializedName("SubscribeType")
  private Double subscribeType = null;

  @SerializedName("UnsubscribedFromID")
  private String unsubscribedFromID = null;

  @SerializedName("UnsubscribedOn")
  private String unsubscribedOn = null;

  @SerializedName("UpdatedOn")
  private String updatedOn = null;

  public Context37 createdOn(String createdOn) {
    this.createdOn = createdOn;
    return this;
  }

   /**
   * 
   * @return createdOn
  **/
  @ApiModelProperty(value = "")
  public String getCreatedOn() {
    return createdOn;
  }

  public void setCreatedOn(String createdOn) {
    this.createdOn = createdOn;
  }

  public Context37 customFields(List<CustomField> customFields) {
    this.customFields = customFields;
    return this;
  }

  public Context37 addCustomFieldsItem(CustomField customFieldsItem) {
    if (this.customFields == null) {
      this.customFields = new ArrayList<CustomField>();
    }
    this.customFields.add(customFieldsItem);
    return this;
  }

   /**
   * 
   * @return customFields
  **/
  @ApiModelProperty(value = "")
  public List<CustomField> getCustomFields() {
    return customFields;
  }

  public void setCustomFields(List<CustomField> customFields) {
    this.customFields = customFields;
  }

  public Context37 email(String email) {
    this.email = email;
    return this;
  }

   /**
   * 
   * @return email
  **/
  @ApiModelProperty(value = "")
  public String getEmail() {
    return email;
  }

  public void setEmail(String email) {
    this.email = email;
  }

  public Context37 ID(String ID) {
    this.ID = ID;
    return this;
  }

   /**
   * 
   * @return ID
  **/
  @ApiModelProperty(value = "")
  public String getID() {
    return ID;
  }

  public void setID(String ID) {
    this.ID = ID;
  }

  public Context37 name(String name) {
    this.name = name;
    return this;
  }

   /**
   * 
   * @return name
  **/
  @ApiModelProperty(value = "")
  public String getName() {
    return name;
  }

  public void setName(String name) {
    this.name = name;
  }

  public Context37 removedOn(String removedOn) {
    this.removedOn = removedOn;
    return this;
  }

   /**
   * 
   * @return removedOn
  **/
  @ApiModelProperty(value = "")
  public String getRemovedOn() {
    return removedOn;
  }

  public void setRemovedOn(String removedOn) {
    this.removedOn = removedOn;
  }

  public Context37 subscribeMethod(Double subscribeMethod) {
    this.subscribeMethod = subscribeMethod;
    return this;
  }

   /**
   * 
   * @return subscribeMethod
  **/
  @ApiModelProperty(value = "")
  public Double getSubscribeMethod() {
    return subscribeMethod;
  }

  public void setSubscribeMethod(Double subscribeMethod) {
    this.subscribeMethod = subscribeMethod;
  }

  public Context37 subscribeType(Double subscribeType) {
    this.subscribeType = subscribeType;
    return this;
  }

   /**
   * 
   * @return subscribeType
  **/
  @ApiModelProperty(value = "")
  public Double getSubscribeType() {
    return subscribeType;
  }

  public void setSubscribeType(Double subscribeType) {
    this.subscribeType = subscribeType;
  }

  public Context37 unsubscribedFromID(String unsubscribedFromID) {
    this.unsubscribedFromID = unsubscribedFromID;
    return this;
  }

   /**
   * 
   * @return unsubscribedFromID
  **/
  @ApiModelProperty(value = "")
  public String getUnsubscribedFromID() {
    return unsubscribedFromID;
  }

  public void setUnsubscribedFromID(String unsubscribedFromID) {
    this.unsubscribedFromID = unsubscribedFromID;
  }

  public Context37 unsubscribedOn(String unsubscribedOn) {
    this.unsubscribedOn = unsubscribedOn;
    return this;
  }

   /**
   * 
   * @return unsubscribedOn
  **/
  @ApiModelProperty(value = "")
  public String getUnsubscribedOn() {
    return unsubscribedOn;
  }

  public void setUnsubscribedOn(String unsubscribedOn) {
    this.unsubscribedOn = unsubscribedOn;
  }

  public Context37 updatedOn(String updatedOn) {
    this.updatedOn = updatedOn;
    return this;
  }

   /**
   * 
   * @return updatedOn
  **/
  @ApiModelProperty(value = "")
  public String getUpdatedOn() {
    return updatedOn;
  }

  public void setUpdatedOn(String updatedOn) {
    this.updatedOn = updatedOn;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Context37 context37 = (Context37) o;
    return Objects.equals(this.createdOn, context37.createdOn) &&
        Objects.equals(this.customFields, context37.customFields) &&
        Objects.equals(this.email, context37.email) &&
        Objects.equals(this.ID, context37.ID) &&
        Objects.equals(this.name, context37.name) &&
        Objects.equals(this.removedOn, context37.removedOn) &&
        Objects.equals(this.subscribeMethod, context37.subscribeMethod) &&
        Objects.equals(this.subscribeType, context37.subscribeType) &&
        Objects.equals(this.unsubscribedFromID, context37.unsubscribedFromID) &&
        Objects.equals(this.unsubscribedOn, context37.unsubscribedOn) &&
        Objects.equals(this.updatedOn, context37.updatedOn);
  }

  @Override
  public int hashCode() {
    return Objects.hash(createdOn, customFields, email, ID, name, removedOn, subscribeMethod, subscribeType, unsubscribedFromID, unsubscribedOn, updatedOn);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class Context37 {\n");
    
    sb.append("    createdOn: ").append(toIndentedString(createdOn)).append("\n");
    sb.append("    customFields: ").append(toIndentedString(customFields)).append("\n");
    sb.append("    email: ").append(toIndentedString(email)).append("\n");
    sb.append("    ID: ").append(toIndentedString(ID)).append("\n");
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    removedOn: ").append(toIndentedString(removedOn)).append("\n");
    sb.append("    subscribeMethod: ").append(toIndentedString(subscribeMethod)).append("\n");
    sb.append("    subscribeType: ").append(toIndentedString(subscribeType)).append("\n");
    sb.append("    unsubscribedFromID: ").append(toIndentedString(unsubscribedFromID)).append("\n");
    sb.append("    unsubscribedOn: ").append(toIndentedString(unsubscribedOn)).append("\n");
    sb.append("    updatedOn: ").append(toIndentedString(updatedOn)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
  
}

