/*
 * Moosend API
 * TODO: Add a description
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.swagger.client.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;

/**
 * Context64
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2017-10-03T15:14:23.257Z")
public class Context64 {
  @SerializedName("EmailsIgnored")
  private Double emailsIgnored = null;

  @SerializedName("EmailsProcessed")
  private Double emailsProcessed = null;

  public Context64 emailsIgnored(Double emailsIgnored) {
    this.emailsIgnored = emailsIgnored;
    return this;
  }

   /**
   * 
   * @return emailsIgnored
  **/
  @ApiModelProperty(value = "")
  public Double getEmailsIgnored() {
    return emailsIgnored;
  }

  public void setEmailsIgnored(Double emailsIgnored) {
    this.emailsIgnored = emailsIgnored;
  }

  public Context64 emailsProcessed(Double emailsProcessed) {
    this.emailsProcessed = emailsProcessed;
    return this;
  }

   /**
   * 
   * @return emailsProcessed
  **/
  @ApiModelProperty(value = "")
  public Double getEmailsProcessed() {
    return emailsProcessed;
  }

  public void setEmailsProcessed(Double emailsProcessed) {
    this.emailsProcessed = emailsProcessed;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Context64 context64 = (Context64) o;
    return Objects.equals(this.emailsIgnored, context64.emailsIgnored) &&
        Objects.equals(this.emailsProcessed, context64.emailsProcessed);
  }

  @Override
  public int hashCode() {
    return Objects.hash(emailsIgnored, emailsProcessed);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class Context64 {\n");
    
    sb.append("    emailsIgnored: ").append(toIndentedString(emailsIgnored)).append("\n");
    sb.append("    emailsProcessed: ").append(toIndentedString(emailsProcessed)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
  
}

