/*
 * Moosend API
 * TODO: Add a description
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.swagger.client.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import io.swagger.client.model.Analytic;
import io.swagger.client.model.Paging;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;

/**
 * Context110
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2017-10-03T15:14:23.257Z")
public class Context110 {
  @SerializedName("Analytics")
  private List<Analytic> analytics = null;

  @SerializedName("Paging")
  private Paging paging = null;

  public Context110 analytics(List<Analytic> analytics) {
    this.analytics = analytics;
    return this;
  }

  public Context110 addAnalyticsItem(Analytic analyticsItem) {
    if (this.analytics == null) {
      this.analytics = new ArrayList<Analytic>();
    }
    this.analytics.add(analyticsItem);
    return this;
  }

   /**
   * 
   * @return analytics
  **/
  @ApiModelProperty(value = "")
  public List<Analytic> getAnalytics() {
    return analytics;
  }

  public void setAnalytics(List<Analytic> analytics) {
    this.analytics = analytics;
  }

  public Context110 paging(Paging paging) {
    this.paging = paging;
    return this;
  }

   /**
   * Get paging
   * @return paging
  **/
  @ApiModelProperty(value = "")
  public Paging getPaging() {
    return paging;
  }

  public void setPaging(Paging paging) {
    this.paging = paging;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Context110 context110 = (Context110) o;
    return Objects.equals(this.analytics, context110.analytics) &&
        Objects.equals(this.paging, context110.paging);
  }

  @Override
  public int hashCode() {
    return Objects.hash(analytics, paging);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class Context110 {\n");
    
    sb.append("    analytics: ").append(toIndentedString(analytics)).append("\n");
    sb.append("    paging: ").append(toIndentedString(paging)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
  
}

