/*
 * Moosend API
 * TODO: Add a description
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.swagger.client.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import io.swagger.client.model.ABCampaignData;
import io.swagger.client.model.MailingList85;
import io.swagger.client.model.ReplyToEmail;
import io.swagger.client.model.Sender;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;

/**
 * Context93
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2017-10-03T15:14:23.257Z")
public class Context93 {
  @SerializedName("ABCampaignData")
  private ABCampaignData abCampaignData = null;

  @SerializedName("ConfirmationTo")
  private String confirmationTo = null;

  @SerializedName("CreatedOn")
  private String createdOn = null;

  @SerializedName("DeliveredOn")
  private String deliveredOn = null;

  @SerializedName("FormatType")
  private Double formatType = null;

  @SerializedName("HTMLContent")
  private String htMLContent = null;

  @SerializedName("ID")
  private String ID = null;

  @SerializedName("IsTransactional")
  private Boolean isTransactional = null;

  @SerializedName("MailingLists")
  private List<MailingList85> mailingLists = null;

  @SerializedName("Name")
  private String name = null;

  @SerializedName("PlainContent")
  private String plainContent = null;

  @SerializedName("ReplyToEmail")
  private ReplyToEmail replyToEmail = null;

  @SerializedName("ScheduledFor")
  private String scheduledFor = null;

  @SerializedName("Sender")
  private Sender sender = null;

  @SerializedName("Status")
  private Double status = null;

  @SerializedName("Subject")
  private String subject = null;

  @SerializedName("Timezone")
  private String timezone = null;

  @SerializedName("UpdatedOn")
  private String updatedOn = null;

  @SerializedName("WebLocation")
  private String webLocation = null;

  public Context93 abCampaignData(ABCampaignData abCampaignData) {
    this.abCampaignData = abCampaignData;
    return this;
  }

   /**
   * Get abCampaignData
   * @return abCampaignData
  **/
  @ApiModelProperty(value = "")
  public ABCampaignData getAbCampaignData() {
    return abCampaignData;
  }

  public void setAbCampaignData(ABCampaignData abCampaignData) {
    this.abCampaignData = abCampaignData;
  }

  public Context93 confirmationTo(String confirmationTo) {
    this.confirmationTo = confirmationTo;
    return this;
  }

   /**
   * 
   * @return confirmationTo
  **/
  @ApiModelProperty(value = "")
  public String getConfirmationTo() {
    return confirmationTo;
  }

  public void setConfirmationTo(String confirmationTo) {
    this.confirmationTo = confirmationTo;
  }

  public Context93 createdOn(String createdOn) {
    this.createdOn = createdOn;
    return this;
  }

   /**
   * 
   * @return createdOn
  **/
  @ApiModelProperty(value = "")
  public String getCreatedOn() {
    return createdOn;
  }

  public void setCreatedOn(String createdOn) {
    this.createdOn = createdOn;
  }

  public Context93 deliveredOn(String deliveredOn) {
    this.deliveredOn = deliveredOn;
    return this;
  }

   /**
   * 
   * @return deliveredOn
  **/
  @ApiModelProperty(value = "")
  public String getDeliveredOn() {
    return deliveredOn;
  }

  public void setDeliveredOn(String deliveredOn) {
    this.deliveredOn = deliveredOn;
  }

  public Context93 formatType(Double formatType) {
    this.formatType = formatType;
    return this;
  }

   /**
   * 
   * @return formatType
  **/
  @ApiModelProperty(value = "")
  public Double getFormatType() {
    return formatType;
  }

  public void setFormatType(Double formatType) {
    this.formatType = formatType;
  }

  public Context93 htMLContent(String htMLContent) {
    this.htMLContent = htMLContent;
    return this;
  }

   /**
   * 
   * @return htMLContent
  **/
  @ApiModelProperty(value = "")
  public String getHtMLContent() {
    return htMLContent;
  }

  public void setHtMLContent(String htMLContent) {
    this.htMLContent = htMLContent;
  }

  public Context93 ID(String ID) {
    this.ID = ID;
    return this;
  }

   /**
   * 
   * @return ID
  **/
  @ApiModelProperty(value = "")
  public String getID() {
    return ID;
  }

  public void setID(String ID) {
    this.ID = ID;
  }

  public Context93 isTransactional(Boolean isTransactional) {
    this.isTransactional = isTransactional;
    return this;
  }

   /**
   * 
   * @return isTransactional
  **/
  @ApiModelProperty(value = "")
  public Boolean getIsTransactional() {
    return isTransactional;
  }

  public void setIsTransactional(Boolean isTransactional) {
    this.isTransactional = isTransactional;
  }

  public Context93 mailingLists(List<MailingList85> mailingLists) {
    this.mailingLists = mailingLists;
    return this;
  }

  public Context93 addMailingListsItem(MailingList85 mailingListsItem) {
    if (this.mailingLists == null) {
      this.mailingLists = new ArrayList<MailingList85>();
    }
    this.mailingLists.add(mailingListsItem);
    return this;
  }

   /**
   * 
   * @return mailingLists
  **/
  @ApiModelProperty(value = "")
  public List<MailingList85> getMailingLists() {
    return mailingLists;
  }

  public void setMailingLists(List<MailingList85> mailingLists) {
    this.mailingLists = mailingLists;
  }

  public Context93 name(String name) {
    this.name = name;
    return this;
  }

   /**
   * 
   * @return name
  **/
  @ApiModelProperty(value = "")
  public String getName() {
    return name;
  }

  public void setName(String name) {
    this.name = name;
  }

  public Context93 plainContent(String plainContent) {
    this.plainContent = plainContent;
    return this;
  }

   /**
   * 
   * @return plainContent
  **/
  @ApiModelProperty(value = "")
  public String getPlainContent() {
    return plainContent;
  }

  public void setPlainContent(String plainContent) {
    this.plainContent = plainContent;
  }

  public Context93 replyToEmail(ReplyToEmail replyToEmail) {
    this.replyToEmail = replyToEmail;
    return this;
  }

   /**
   * Get replyToEmail
   * @return replyToEmail
  **/
  @ApiModelProperty(value = "")
  public ReplyToEmail getReplyToEmail() {
    return replyToEmail;
  }

  public void setReplyToEmail(ReplyToEmail replyToEmail) {
    this.replyToEmail = replyToEmail;
  }

  public Context93 scheduledFor(String scheduledFor) {
    this.scheduledFor = scheduledFor;
    return this;
  }

   /**
   * 
   * @return scheduledFor
  **/
  @ApiModelProperty(value = "")
  public String getScheduledFor() {
    return scheduledFor;
  }

  public void setScheduledFor(String scheduledFor) {
    this.scheduledFor = scheduledFor;
  }

  public Context93 sender(Sender sender) {
    this.sender = sender;
    return this;
  }

   /**
   * Get sender
   * @return sender
  **/
  @ApiModelProperty(value = "")
  public Sender getSender() {
    return sender;
  }

  public void setSender(Sender sender) {
    this.sender = sender;
  }

  public Context93 status(Double status) {
    this.status = status;
    return this;
  }

   /**
   * 
   * @return status
  **/
  @ApiModelProperty(value = "")
  public Double getStatus() {
    return status;
  }

  public void setStatus(Double status) {
    this.status = status;
  }

  public Context93 subject(String subject) {
    this.subject = subject;
    return this;
  }

   /**
   * 
   * @return subject
  **/
  @ApiModelProperty(value = "")
  public String getSubject() {
    return subject;
  }

  public void setSubject(String subject) {
    this.subject = subject;
  }

  public Context93 timezone(String timezone) {
    this.timezone = timezone;
    return this;
  }

   /**
   * 
   * @return timezone
  **/
  @ApiModelProperty(value = "")
  public String getTimezone() {
    return timezone;
  }

  public void setTimezone(String timezone) {
    this.timezone = timezone;
  }

  public Context93 updatedOn(String updatedOn) {
    this.updatedOn = updatedOn;
    return this;
  }

   /**
   * 
   * @return updatedOn
  **/
  @ApiModelProperty(value = "")
  public String getUpdatedOn() {
    return updatedOn;
  }

  public void setUpdatedOn(String updatedOn) {
    this.updatedOn = updatedOn;
  }

  public Context93 webLocation(String webLocation) {
    this.webLocation = webLocation;
    return this;
  }

   /**
   * 
   * @return webLocation
  **/
  @ApiModelProperty(value = "")
  public String getWebLocation() {
    return webLocation;
  }

  public void setWebLocation(String webLocation) {
    this.webLocation = webLocation;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Context93 context93 = (Context93) o;
    return Objects.equals(this.abCampaignData, context93.abCampaignData) &&
        Objects.equals(this.confirmationTo, context93.confirmationTo) &&
        Objects.equals(this.createdOn, context93.createdOn) &&
        Objects.equals(this.deliveredOn, context93.deliveredOn) &&
        Objects.equals(this.formatType, context93.formatType) &&
        Objects.equals(this.htMLContent, context93.htMLContent) &&
        Objects.equals(this.ID, context93.ID) &&
        Objects.equals(this.isTransactional, context93.isTransactional) &&
        Objects.equals(this.mailingLists, context93.mailingLists) &&
        Objects.equals(this.name, context93.name) &&
        Objects.equals(this.plainContent, context93.plainContent) &&
        Objects.equals(this.replyToEmail, context93.replyToEmail) &&
        Objects.equals(this.scheduledFor, context93.scheduledFor) &&
        Objects.equals(this.sender, context93.sender) &&
        Objects.equals(this.status, context93.status) &&
        Objects.equals(this.subject, context93.subject) &&
        Objects.equals(this.timezone, context93.timezone) &&
        Objects.equals(this.updatedOn, context93.updatedOn) &&
        Objects.equals(this.webLocation, context93.webLocation);
  }

  @Override
  public int hashCode() {
    return Objects.hash(abCampaignData, confirmationTo, createdOn, deliveredOn, formatType, htMLContent, ID, isTransactional, mailingLists, name, plainContent, replyToEmail, scheduledFor, sender, status, subject, timezone, updatedOn, webLocation);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class Context93 {\n");
    
    sb.append("    abCampaignData: ").append(toIndentedString(abCampaignData)).append("\n");
    sb.append("    confirmationTo: ").append(toIndentedString(confirmationTo)).append("\n");
    sb.append("    createdOn: ").append(toIndentedString(createdOn)).append("\n");
    sb.append("    deliveredOn: ").append(toIndentedString(deliveredOn)).append("\n");
    sb.append("    formatType: ").append(toIndentedString(formatType)).append("\n");
    sb.append("    htMLContent: ").append(toIndentedString(htMLContent)).append("\n");
    sb.append("    ID: ").append(toIndentedString(ID)).append("\n");
    sb.append("    isTransactional: ").append(toIndentedString(isTransactional)).append("\n");
    sb.append("    mailingLists: ").append(toIndentedString(mailingLists)).append("\n");
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    plainContent: ").append(toIndentedString(plainContent)).append("\n");
    sb.append("    replyToEmail: ").append(toIndentedString(replyToEmail)).append("\n");
    sb.append("    scheduledFor: ").append(toIndentedString(scheduledFor)).append("\n");
    sb.append("    sender: ").append(toIndentedString(sender)).append("\n");
    sb.append("    status: ").append(toIndentedString(status)).append("\n");
    sb.append("    subject: ").append(toIndentedString(subject)).append("\n");
    sb.append("    timezone: ").append(toIndentedString(timezone)).append("\n");
    sb.append("    updatedOn: ").append(toIndentedString(updatedOn)).append("\n");
    sb.append("    webLocation: ").append(toIndentedString(webLocation)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
  
}

