/*
 * Moosend API
 * TODO: Add a description
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.swagger.client.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;

/**
 * Criterion
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2017-10-03T15:14:23.257Z")
public class Criterion {
  @SerializedName("Comparer")
  private Double comparer = null;

  @SerializedName("CustomFieldID")
  private String customFieldID = null;

  @SerializedName("DateFrom")
  private String dateFrom = null;

  @SerializedName("DateTo")
  private String dateTo = null;

  @SerializedName("Field")
  private Double field = null;

  @SerializedName("ID")
  private Double ID = null;

  @SerializedName("Properties")
  private String properties = null;

  @SerializedName("SegmentID")
  private Double segmentID = null;

  @SerializedName("Subscriteria")
  private String subscriteria = null;

  @SerializedName("Value")
  private String value = null;

  public Criterion comparer(Double comparer) {
    this.comparer = comparer;
    return this;
  }

   /**
   * 
   * @return comparer
  **/
  @ApiModelProperty(value = "")
  public Double getComparer() {
    return comparer;
  }

  public void setComparer(Double comparer) {
    this.comparer = comparer;
  }

  public Criterion customFieldID(String customFieldID) {
    this.customFieldID = customFieldID;
    return this;
  }

   /**
   * 
   * @return customFieldID
  **/
  @ApiModelProperty(value = "")
  public String getCustomFieldID() {
    return customFieldID;
  }

  public void setCustomFieldID(String customFieldID) {
    this.customFieldID = customFieldID;
  }

  public Criterion dateFrom(String dateFrom) {
    this.dateFrom = dateFrom;
    return this;
  }

   /**
   * 
   * @return dateFrom
  **/
  @ApiModelProperty(value = "")
  public String getDateFrom() {
    return dateFrom;
  }

  public void setDateFrom(String dateFrom) {
    this.dateFrom = dateFrom;
  }

  public Criterion dateTo(String dateTo) {
    this.dateTo = dateTo;
    return this;
  }

   /**
   * 
   * @return dateTo
  **/
  @ApiModelProperty(value = "")
  public String getDateTo() {
    return dateTo;
  }

  public void setDateTo(String dateTo) {
    this.dateTo = dateTo;
  }

  public Criterion field(Double field) {
    this.field = field;
    return this;
  }

   /**
   * 
   * @return field
  **/
  @ApiModelProperty(value = "")
  public Double getField() {
    return field;
  }

  public void setField(Double field) {
    this.field = field;
  }

  public Criterion ID(Double ID) {
    this.ID = ID;
    return this;
  }

   /**
   * 
   * @return ID
  **/
  @ApiModelProperty(value = "")
  public Double getID() {
    return ID;
  }

  public void setID(Double ID) {
    this.ID = ID;
  }

  public Criterion properties(String properties) {
    this.properties = properties;
    return this;
  }

   /**
   * 
   * @return properties
  **/
  @ApiModelProperty(value = "")
  public String getProperties() {
    return properties;
  }

  public void setProperties(String properties) {
    this.properties = properties;
  }

  public Criterion segmentID(Double segmentID) {
    this.segmentID = segmentID;
    return this;
  }

   /**
   * 
   * @return segmentID
  **/
  @ApiModelProperty(value = "")
  public Double getSegmentID() {
    return segmentID;
  }

  public void setSegmentID(Double segmentID) {
    this.segmentID = segmentID;
  }

  public Criterion subscriteria(String subscriteria) {
    this.subscriteria = subscriteria;
    return this;
  }

   /**
   * 
   * @return subscriteria
  **/
  @ApiModelProperty(value = "")
  public String getSubscriteria() {
    return subscriteria;
  }

  public void setSubscriteria(String subscriteria) {
    this.subscriteria = subscriteria;
  }

  public Criterion value(String value) {
    this.value = value;
    return this;
  }

   /**
   * 
   * @return value
  **/
  @ApiModelProperty(value = "")
  public String getValue() {
    return value;
  }

  public void setValue(String value) {
    this.value = value;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Criterion criterion = (Criterion) o;
    return Objects.equals(this.comparer, criterion.comparer) &&
        Objects.equals(this.customFieldID, criterion.customFieldID) &&
        Objects.equals(this.dateFrom, criterion.dateFrom) &&
        Objects.equals(this.dateTo, criterion.dateTo) &&
        Objects.equals(this.field, criterion.field) &&
        Objects.equals(this.ID, criterion.ID) &&
        Objects.equals(this.properties, criterion.properties) &&
        Objects.equals(this.segmentID, criterion.segmentID) &&
        Objects.equals(this.subscriteria, criterion.subscriteria) &&
        Objects.equals(this.value, criterion.value);
  }

  @Override
  public int hashCode() {
    return Objects.hash(comparer, customFieldID, dateFrom, dateTo, field, ID, properties, segmentID, subscriteria, value);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class Criterion {\n");
    
    sb.append("    comparer: ").append(toIndentedString(comparer)).append("\n");
    sb.append("    customFieldID: ").append(toIndentedString(customFieldID)).append("\n");
    sb.append("    dateFrom: ").append(toIndentedString(dateFrom)).append("\n");
    sb.append("    dateTo: ").append(toIndentedString(dateTo)).append("\n");
    sb.append("    field: ").append(toIndentedString(field)).append("\n");
    sb.append("    ID: ").append(toIndentedString(ID)).append("\n");
    sb.append("    properties: ").append(toIndentedString(properties)).append("\n");
    sb.append("    segmentID: ").append(toIndentedString(segmentID)).append("\n");
    sb.append("    subscriteria: ").append(toIndentedString(subscriteria)).append("\n");
    sb.append("    value: ").append(toIndentedString(value)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
  
}

