/*
 * Moosend API
 * TODO: Add a description
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.swagger.client.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;

/**
 * MailingList69
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2017-10-03T15:14:23.257Z")
public class MailingList69 {
  @SerializedName("ActiveMemberCount")
  private Double activeMemberCount = null;

  @SerializedName("BouncedMemberCount")
  private Double bouncedMemberCount = null;

  @SerializedName("CreatedBy")
  private String createdBy = null;

  @SerializedName("CreatedOn")
  private String createdOn = null;

  @SerializedName("CustomFieldsDefinition")
  private List<Object> customFieldsDefinition = null;

  @SerializedName("ID")
  private String ID = null;

  @SerializedName("ImportOperation")
  private String importOperation = null;

  @SerializedName("Name")
  private String name = null;

  @SerializedName("RemovedMemberCount")
  private Double removedMemberCount = null;

  @SerializedName("Status")
  private Double status = null;

  @SerializedName("UnsubscribedMemberCount")
  private Double unsubscribedMemberCount = null;

  @SerializedName("UpdatedBy")
  private String updatedBy = null;

  @SerializedName("UpdatedOn")
  private String updatedOn = null;

  public MailingList69 activeMemberCount(Double activeMemberCount) {
    this.activeMemberCount = activeMemberCount;
    return this;
  }

   /**
   * 
   * @return activeMemberCount
  **/
  @ApiModelProperty(value = "")
  public Double getActiveMemberCount() {
    return activeMemberCount;
  }

  public void setActiveMemberCount(Double activeMemberCount) {
    this.activeMemberCount = activeMemberCount;
  }

  public MailingList69 bouncedMemberCount(Double bouncedMemberCount) {
    this.bouncedMemberCount = bouncedMemberCount;
    return this;
  }

   /**
   * 
   * @return bouncedMemberCount
  **/
  @ApiModelProperty(value = "")
  public Double getBouncedMemberCount() {
    return bouncedMemberCount;
  }

  public void setBouncedMemberCount(Double bouncedMemberCount) {
    this.bouncedMemberCount = bouncedMemberCount;
  }

  public MailingList69 createdBy(String createdBy) {
    this.createdBy = createdBy;
    return this;
  }

   /**
   * 
   * @return createdBy
  **/
  @ApiModelProperty(value = "")
  public String getCreatedBy() {
    return createdBy;
  }

  public void setCreatedBy(String createdBy) {
    this.createdBy = createdBy;
  }

  public MailingList69 createdOn(String createdOn) {
    this.createdOn = createdOn;
    return this;
  }

   /**
   * 
   * @return createdOn
  **/
  @ApiModelProperty(value = "")
  public String getCreatedOn() {
    return createdOn;
  }

  public void setCreatedOn(String createdOn) {
    this.createdOn = createdOn;
  }

  public MailingList69 customFieldsDefinition(List<Object> customFieldsDefinition) {
    this.customFieldsDefinition = customFieldsDefinition;
    return this;
  }

  public MailingList69 addCustomFieldsDefinitionItem(Object customFieldsDefinitionItem) {
    if (this.customFieldsDefinition == null) {
      this.customFieldsDefinition = new ArrayList<Object>();
    }
    this.customFieldsDefinition.add(customFieldsDefinitionItem);
    return this;
  }

   /**
   * 
   * @return customFieldsDefinition
  **/
  @ApiModelProperty(value = "")
  public List<Object> getCustomFieldsDefinition() {
    return customFieldsDefinition;
  }

  public void setCustomFieldsDefinition(List<Object> customFieldsDefinition) {
    this.customFieldsDefinition = customFieldsDefinition;
  }

  public MailingList69 ID(String ID) {
    this.ID = ID;
    return this;
  }

   /**
   * 
   * @return ID
  **/
  @ApiModelProperty(value = "")
  public String getID() {
    return ID;
  }

  public void setID(String ID) {
    this.ID = ID;
  }

  public MailingList69 importOperation(String importOperation) {
    this.importOperation = importOperation;
    return this;
  }

   /**
   * 
   * @return importOperation
  **/
  @ApiModelProperty(value = "")
  public String getImportOperation() {
    return importOperation;
  }

  public void setImportOperation(String importOperation) {
    this.importOperation = importOperation;
  }

  public MailingList69 name(String name) {
    this.name = name;
    return this;
  }

   /**
   * 
   * @return name
  **/
  @ApiModelProperty(value = "")
  public String getName() {
    return name;
  }

  public void setName(String name) {
    this.name = name;
  }

  public MailingList69 removedMemberCount(Double removedMemberCount) {
    this.removedMemberCount = removedMemberCount;
    return this;
  }

   /**
   * 
   * @return removedMemberCount
  **/
  @ApiModelProperty(value = "")
  public Double getRemovedMemberCount() {
    return removedMemberCount;
  }

  public void setRemovedMemberCount(Double removedMemberCount) {
    this.removedMemberCount = removedMemberCount;
  }

  public MailingList69 status(Double status) {
    this.status = status;
    return this;
  }

   /**
   * 
   * @return status
  **/
  @ApiModelProperty(value = "")
  public Double getStatus() {
    return status;
  }

  public void setStatus(Double status) {
    this.status = status;
  }

  public MailingList69 unsubscribedMemberCount(Double unsubscribedMemberCount) {
    this.unsubscribedMemberCount = unsubscribedMemberCount;
    return this;
  }

   /**
   * 
   * @return unsubscribedMemberCount
  **/
  @ApiModelProperty(value = "")
  public Double getUnsubscribedMemberCount() {
    return unsubscribedMemberCount;
  }

  public void setUnsubscribedMemberCount(Double unsubscribedMemberCount) {
    this.unsubscribedMemberCount = unsubscribedMemberCount;
  }

  public MailingList69 updatedBy(String updatedBy) {
    this.updatedBy = updatedBy;
    return this;
  }

   /**
   * 
   * @return updatedBy
  **/
  @ApiModelProperty(value = "")
  public String getUpdatedBy() {
    return updatedBy;
  }

  public void setUpdatedBy(String updatedBy) {
    this.updatedBy = updatedBy;
  }

  public MailingList69 updatedOn(String updatedOn) {
    this.updatedOn = updatedOn;
    return this;
  }

   /**
   * 
   * @return updatedOn
  **/
  @ApiModelProperty(value = "")
  public String getUpdatedOn() {
    return updatedOn;
  }

  public void setUpdatedOn(String updatedOn) {
    this.updatedOn = updatedOn;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    MailingList69 mailingList69 = (MailingList69) o;
    return Objects.equals(this.activeMemberCount, mailingList69.activeMemberCount) &&
        Objects.equals(this.bouncedMemberCount, mailingList69.bouncedMemberCount) &&
        Objects.equals(this.createdBy, mailingList69.createdBy) &&
        Objects.equals(this.createdOn, mailingList69.createdOn) &&
        Objects.equals(this.customFieldsDefinition, mailingList69.customFieldsDefinition) &&
        Objects.equals(this.ID, mailingList69.ID) &&
        Objects.equals(this.importOperation, mailingList69.importOperation) &&
        Objects.equals(this.name, mailingList69.name) &&
        Objects.equals(this.removedMemberCount, mailingList69.removedMemberCount) &&
        Objects.equals(this.status, mailingList69.status) &&
        Objects.equals(this.unsubscribedMemberCount, mailingList69.unsubscribedMemberCount) &&
        Objects.equals(this.updatedBy, mailingList69.updatedBy) &&
        Objects.equals(this.updatedOn, mailingList69.updatedOn);
  }

  @Override
  public int hashCode() {
    return Objects.hash(activeMemberCount, bouncedMemberCount, createdBy, createdOn, customFieldsDefinition, ID, importOperation, name, removedMemberCount, status, unsubscribedMemberCount, updatedBy, updatedOn);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class MailingList69 {\n");
    
    sb.append("    activeMemberCount: ").append(toIndentedString(activeMemberCount)).append("\n");
    sb.append("    bouncedMemberCount: ").append(toIndentedString(bouncedMemberCount)).append("\n");
    sb.append("    createdBy: ").append(toIndentedString(createdBy)).append("\n");
    sb.append("    createdOn: ").append(toIndentedString(createdOn)).append("\n");
    sb.append("    customFieldsDefinition: ").append(toIndentedString(customFieldsDefinition)).append("\n");
    sb.append("    ID: ").append(toIndentedString(ID)).append("\n");
    sb.append("    importOperation: ").append(toIndentedString(importOperation)).append("\n");
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    removedMemberCount: ").append(toIndentedString(removedMemberCount)).append("\n");
    sb.append("    status: ").append(toIndentedString(status)).append("\n");
    sb.append("    unsubscribedMemberCount: ").append(toIndentedString(unsubscribedMemberCount)).append("\n");
    sb.append("    updatedBy: ").append(toIndentedString(updatedBy)).append("\n");
    sb.append("    updatedOn: ").append(toIndentedString(updatedOn)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
  
}

