/*
 * Moosend API
 * TODO: Add a description
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.swagger.client.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;

/**
 * MailingLists
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2017-10-03T15:14:23.257Z")
public class MailingLists {
  @SerializedName("MailingListId")
  private String mailingListId = null;

  @SerializedName("SegmentId")
  private Double segmentId = null;

  public MailingLists mailingListId(String mailingListId) {
    this.mailingListId = mailingListId;
    return this;
  }

   /**
   * A Mailing list id
   * @return mailingListId
  **/
  @ApiModelProperty(required = true, value = "A Mailing list id")
  public String getMailingListId() {
    return mailingListId;
  }

  public void setMailingListId(String mailingListId) {
    this.mailingListId = mailingListId;
  }

  public MailingLists segmentId(Double segmentId) {
    this.segmentId = segmentId;
    return this;
  }

   /**
   * Possible values : (whatever, random, fuck)
   * @return segmentId
  **/
  @ApiModelProperty(value = "Possible values : (whatever, random, fuck)")
  public Double getSegmentId() {
    return segmentId;
  }

  public void setSegmentId(Double segmentId) {
    this.segmentId = segmentId;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    MailingLists mailingLists = (MailingLists) o;
    return Objects.equals(this.mailingListId, mailingLists.mailingListId) &&
        Objects.equals(this.segmentId, mailingLists.segmentId);
  }

  @Override
  public int hashCode() {
    return Objects.hash(mailingListId, segmentId);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class MailingLists {\n");
    
    sb.append("    mailingListId: ").append(toIndentedString(mailingListId)).append("\n");
    sb.append("    segmentId: ").append(toIndentedString(segmentId)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
  
}

