/*
 * Moosend API
 * TODO: Add a description
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.swagger.client.model;

import java.util.Objects;
import com.google.gson.annotations.SerializedName;

import java.io.IOException;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;

/**
 * Gets or Sets WithStatistics
 */
@JsonAdapter(WithStatistics.Adapter.class)
public enum WithStatistics {
  
  TRUE("true"),
  
  FALSE("false");

  private String value;

  WithStatistics(String value) {
    this.value = value;
  }

  public String getValue() {
    return value;
  }

  @Override
  public String toString() {
    return String.valueOf(value);
  }

  public static WithStatistics fromValue(String text) {
    for (WithStatistics b : WithStatistics.values()) {
      if (String.valueOf(b.value).equals(text)) {
        return b;
      }
    }
    return null;
  }

  public static class Adapter extends TypeAdapter<WithStatistics> {
    @Override
    public void write(final JsonWriter jsonWriter, final WithStatistics enumeration) throws IOException {
      jsonWriter.value(enumeration.getValue());
    }

    @Override
    public WithStatistics read(final JsonReader jsonReader) throws IOException {
      String value = jsonReader.nextString();
      return WithStatistics.fromValue(String.valueOf(value));
    }
  }
}

